version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      # Optional: check Node.js version if using custom image
      - node -v || echo "Node.js not found, ensure your custom image has Node.js installed"
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Running build"
      - npm run build || echo "No build step"

artifacts:
  files:
    - '**/*'


