version: 0.2

phases:
  pre_build:
    commands:
      - echo "=== Pre-build phase ==="
      # Check Node.js and npm versions; install if missing
      - if ! command -v node >/dev/null 2>&1; then
          echo "Node.js not found. Please use an image with Node.js installed.";
          exit 1;
        fi
      - node -v
      - npm -v
  install:
    commands:
      - echo "=== Install dependencies ==="
      # Remove existing modules and lock file to avoid conflicts
      - rm -rf node_modules package-lock.json || true
      # Set unsafe permissions to prevent permission errors
      - npm config set unsafe-perm true
      # Install dependencies, retry on failure
      - |
        for i in 1 2 3; do
          npm install && break || echo "npm install failed, retrying ($i/3)"
        done
  build:
    commands:
      - echo "=== Build phase ==="
      - npm run build || echo "No build step defined"

artifacts:
  files:
    - '**/*'


