version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm ci
  build:
    commands:
      - echo "Building app"
      - npm run build || echo "No build step defined"
  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - package.json
    - package-lock.json
    - dist/**/*
  discard-paths: no
